# Generated by Django 6.0.5 on 2026-05-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_name_mr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_name_a2070e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_created_ddfb00_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='product',
            name='booking_contact_name',
            field=models.CharField(default='Manjushri', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='booking_contact_number',
            field=models.CharField(default='8983341944', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='dp_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DP Price (₹)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_quality_policy',
            field=models.CharField(default='100% Premium Quality Guaranteed', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(default='Strict No-Return Policy applies.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='security_measure',
            field=models.CharField(default='Package opening video is compulsory for any damage claims.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_policy',
            field=models.CharField(default='🔥 FREE SHIPPING ALL OVER INDIA 🔥', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a product demonstration video', null=True, upload_to='products/videos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_mr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Write only unique details here (e.g., fabric type, design details)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Offer Price (₹)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='shop.product'),
        ),
    ]
