# Generated by Django 6.0.5 on 2026-05-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimage_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Alternate Booking No, Festive Offer, Fabric Care', max_length=100)),
                ('detail', models.CharField(help_text='The actual note or phone number details', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_policies', to='shop.product')),
            ],
        ),
    ]
