# Generated by Django 6.0.5 on 2026-05-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productpolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dp_price',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_policies_and_notes',
            field=models.TextField(blank=True, help_text='Add any extra booking numbers or custom notices here. Each note on a new line.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (₹)'),
        ),
        migrations.DeleteModel(
            name='ProductPolicy',
        ),
    ]
