# Generated by Django 6.0.5 on 2026-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_dp_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, help_text='Color name for this thumbnail variant (e.g., Royal Blue, Ruby Red)', max_length=100, null=True),
        ),
    ]
