# Generated by Django 6.0.5 on 2026-05-31 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('house_no_flat', models.CharField(blank=True, max_length=255, null=True, verbose_name='House No / Flat')),
                ('address_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address / Street')),
                ('landmark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Near By Landmark')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City Name')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pin Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
